### ISSUE TITLE
Create a team on EasyEDA

### ISSUE THREAD

**Issue by yusufyilmazf** [octoposprime/op-pcb#18]
An OctopOS-EM team will be created on EasyEDA

**Comment by yavuz-yusuf** [comment]
https://u.easyeda.com/octopos-em

**Comment by yavuz-yusuf** [comment]
https://u.easyeda.com/octopos-em

**Comment by yusufyilmazf** [comment]
Please provide more detailed information about the link.

**Comment by yavuz-yusuf** [comment]
Here is out team's home page link. You can view our team on EasyEDA from this link: https://u.easyeda.com/octopos-em
