### ISSUE TITLE
The completion of EasyEDA training

### ISSUE THREAD

**Issue by baburakbas** [octoposprime/op-pcb#29]
Complete this training series published on EasyEDA's own page : 

https://www.youtube.com/watch?v=MsuR6W-jN5M&list=PLbKMtvtYbdPMZfzGuVTdc0MWKrFvU4nsu

**Comment by husamettinarabaci** [comment]
Please add an estimated time.

**Comment by krmlp** [comment]
I successfully completed the EasyEDA training.
