### ISSUE TITLE
The completion of EasyEDA training.

### ISSUE THREAD

**Issue by baburakbas** [octoposprime/op-pcb#30]
Complete this training series published on EasyEDA's own page : 

https://www.youtube.com/watch?v=MsuR6W-jN5M&list=PLbKMtvtYbdPMZfzGuVTdc0MWKrFvU4nsu

**Comment by husamettinarabaci** [comment]
Please add an estimated time.

**Comment by ahmetarabaci42** [comment]
I didn't watch the youtube video that we were told to watch in the Issue, because I don't speak English, but I watched another youtube video that @yusufyilmazf specially recommended.

**Comment by ahmetarabaci42** [comment]
EasyEda tutorial video was watched and the use of the program interface was reinforced with practices
