### ISSUE TITLE
The completion of EasyEDA training.

### ISSUE THREAD

**Issue by baburakbas** [octoposprime/op-pcb#31]
Complete this training series published on EasyEDA's own page :

https://www.youtube.com/watch?v=MsuR6W-jN5M&list=PLbKMtvtYbdPMZfzGuVTdc0MWKrFvU4nsu

**Comment by husamettinarabaci** [comment]
Please add an estimated time.
For ex:
Total hours of the series X 3

**Comment by samedfenerli** [comment]
The practices performed in the training were instructive, I completed them successfully. I think it will benefit me in the field of electronic card design in the future.
