### ISSUE TITLE
Request for File Hierarchy Fix

### ISSUE THREAD

**Issue by yusufyilmazf** [octoposprime/op-pcb#38]
The desired file hierarchy in the op-pcb repository

projects/
│
├── project1/
│   ├── project1.md
│
│
├── project2/
│   ├── project2.md
│
│
├── project3/
│   ├── project3.md
│
│   
└── README.md

**Comment by yavuz-yusuf** [comment]
I fixed the file hierarchy

**Comment by yusufyilmazf** [comment]
please check file hierarchy structure

**Comment by yavuz-yusuf** [comment]
I fixed the file hierarchy
